// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class Banner
    {
        public Banner()
        {
            BannerLocalizeds = new HashSet<BannerLocalized>();
        }

        public int Id { get; set; }
        public int PageId { get; set; }
        public string Photo { get; set; }
        public string CustomField { get; set; }
        public int DisplayOrder { get; set; }
        public bool? Active { get; set; }

        public virtual SitePage Page { get; set; }
        public virtual ICollection<BannerLocalized> BannerLocalizeds { get; set; }
    }
}