// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class Career
    {
        public Career()
        {
            CareerLocalizeds = new HashSet<CareerLocalized>();
        }

        public int Id { get; set; }
        public int CityId { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public int DisplayOrder { get; set; }
        public DateTime DateSubmitted { get; set; }

        public virtual City City { get; set; }
        public virtual ICollection<CareerLocalized> CareerLocalizeds { get; set; }
    }
}