// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class CityLocalized
    {
        public int LanguageId { get; set; }
        public int CityId { get; set; }
        public string Title { get; set; }

        public virtual City City { get; set; }
        public virtual Language Language { get; set; }
    }
}