// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class Event
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public string Alt { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public int DisplayOrder { get; set; }
        public bool? Active { get; set; }
    }
}