// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class Faq
    {
        public Faq()
        {
            FaqLocalizeds = new HashSet<FaqLocalized>();
        }

        public int Id { get; set; }
        public int? CategoryId { get; set; }
        public string Name { get; set; }
        public bool? Active { get; set; }
        public int DisplayOrder { get; set; }

        public virtual FaqCategory Category { get; set; }
        public virtual ICollection<FaqLocalized> FaqLocalizeds { get; set; }
    }
}