// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class FaqCategory
    {
        public FaqCategory()
        {
            FaqCategoryLocalizeds = new HashSet<FaqCategoryLocalized>();
            Faqs = new HashSet<Faq>();
        }

        public int Id { get; set; }
        public string UrlName { get; set; }

        public virtual ICollection<FaqCategoryLocalized> FaqCategoryLocalizeds { get; set; }
        public virtual ICollection<Faq> Faqs { get; set; }
    }
}