// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class FaqLocalized
    {
        public int FaqId { get; set; }
        public int LanguageId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }

        public virtual Faq Faq { get; set; }
        public virtual Language Language { get; set; }
    }
}