// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class HomeBanner
    {
        public HomeBanner()
        {
            HomeBannerLocalizeds = new HashSet<HomeBannerLocalized>();
        }

        public int Id { get; set; }
        public string Photo { get; set; }
        public int DisplayOrder { get; set; }
        public bool? Active { get; set; }
        public string VideoUrl { get; set; }
        public string Link { get; set; }

        public virtual ICollection<HomeBannerLocalized> HomeBannerLocalizeds { get; set; }
    }
}