// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class HomeBannerLocalized
    {
        public int LanguageId { get; set; }
        public int HomeBannerId { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string LinkText { get; set; }

        public virtual HomeBanner HomeBanner { get; set; }
        public virtual Language Language { get; set; }
    }
}