// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class InfoPage
    {
        public InfoPage()
        {
            InfoPageLocalizeds = new HashSet<InfoPageLocalized>();
        }

        public int Id { get; set; }
        public int? CategoryId { get; set; }
        public string UrlName { get; set; }
        public bool? Active { get; set; }
        public string Banner { get; set; }
        public int DisplayOrder { get; set; }

        public virtual InfoPageCategory Category { get; set; }
        public virtual ICollection<InfoPageLocalized> InfoPageLocalizeds { get; set; }
    }
}