// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class Language
    {
        public Language()
        {
            AlbumLocalizeds = new HashSet<AlbumLocalized>();
            BannerLocalizeds = new HashSet<BannerLocalized>();
            CareerLocalizeds = new HashSet<CareerLocalized>();
            CityLocalizeds = new HashSet<CityLocalized>();
            FaqCategoryLocalizeds = new HashSet<FaqCategoryLocalized>();
            FaqLocalizeds = new HashSet<FaqLocalized>();
            HomeBannerLocalizeds = new HashSet<HomeBannerLocalized>();
            InfoPageCategoryLocalizeds = new HashSet<InfoPageCategoryLocalized>();
            InfoPageLocalizeds = new HashSet<InfoPageLocalized>();
            MetaTagLocalizeds = new HashSet<MetaTagLocalized>();
            NewsLocalizeds = new HashSet<NewsLocalized>();
        }

        public int Id { get; set; }
        public string LocalName { get; set; }
        public string CultureName { get; set; }
        public string FriendlyName { get; set; }
        public bool Active { get; set; }
        public int DisplayOrder { get; set; }

        public virtual ICollection<AlbumLocalized> AlbumLocalizeds { get; set; }
        public virtual ICollection<BannerLocalized> BannerLocalizeds { get; set; }
        public virtual ICollection<CareerLocalized> CareerLocalizeds { get; set; }
        public virtual ICollection<CityLocalized> CityLocalizeds { get; set; }
        public virtual ICollection<FaqCategoryLocalized> FaqCategoryLocalizeds { get; set; }
        public virtual ICollection<FaqLocalized> FaqLocalizeds { get; set; }
        public virtual ICollection<HomeBannerLocalized> HomeBannerLocalizeds { get; set; }
        public virtual ICollection<InfoPageCategoryLocalized> InfoPageCategoryLocalizeds { get; set; }
        public virtual ICollection<InfoPageLocalized> InfoPageLocalizeds { get; set; }
        public virtual ICollection<MetaTagLocalized> MetaTagLocalizeds { get; set; }
        public virtual ICollection<NewsLocalized> NewsLocalizeds { get; set; }
    }
}