// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class MenuItem
    {
        public int Id { get; set; }
        public int? SectionId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public decimal Price { get; set; }
        public int? DisplayOrder { get; set; }
        public bool? Active { get; set; }

        public virtual MenuSection Section { get; set; }
    }
}