// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class MetaTagLocalized
    {
        public int MetaTagId { get; set; }
        public int LanguageId { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeywords { get; set; }

        public virtual Language Language { get; set; }
        public virtual MetaTag MetaTag { get; set; }
    }
}