// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class MetaTag
    {
        public MetaTag()
        {
            MetaTagLocalizeds = new HashSet<MetaTagLocalized>();
        }

        public int Id { get; set; }
        public int PageId { get; set; }

        public virtual SitePage Page { get; set; }
        public virtual ICollection<MetaTagLocalized> MetaTagLocalizeds { get; set; }
    }
}