// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class News
    {
        public News()
        {
            NewsLocalizeds = new HashSet<NewsLocalized>();
        }

        public int Id { get; set; }
        public DateTime NewsDate { get; set; }
        public int? GroupId { get; set; }
        public string UrlName { get; set; }
        public string Photo { get; set; }
        public string Thumbnail { get; set; }
        public bool? Active { get; set; }

        public virtual ICollection<NewsLocalized> NewsLocalizeds { get; set; }
    }
}