// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class Setting
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public int DataType { get; set; }

        public virtual SettingCategory Category { get; set; }
    }
}