// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class SocialLink
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public int? GroupId { get; set; }
        public string Link { get; set; }
        public string CssClass { get; set; }
        public bool? Active { get; set; }
    }
}