// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models
{
    public partial class Testimonial
    {
        public int Id { get; set; }
        public int TestimonialSourceId { get; set; }
        public DateTime Date { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public int DisplayOrder { get; set; }
        public bool Active { get; set; }

        public virtual TestimonialSource TestimonialSource { get; set; }
    }
}