//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicData.Admin.Controls.Localized
{


    public partial class LocalizedItem
    {

        /// <summary>
        /// LocalizedAlbum control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DynamicData.Admin.Controls.Localized.AlbumItem LocalizedAlbum;

        /// <summary>
        /// LocalizedMetaTag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DynamicData.Admin.Controls.Localized.LocalizedMetaTag LocalizedMetaTag;

        /// <summary>
        /// LocalizedNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DynamicData.Admin.Controls.Localized.LocalizedNewsItem LocalizedNews;
    }
}
