//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicData.Admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banner()
        {
            this.BannerLocalizeds = new HashSet<BannerLocalized>();
        }
    
        public int Id { get; set; }
        public int PageId { get; set; }
        public string Photo { get; set; }
        public string CustomField { get; set; }
        public int DisplayOrder { get; set; }
        public bool Active { get; set; }
    
        public virtual SitePage SitePage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BannerLocalized> BannerLocalizeds { get; set; }
    }
}
