//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicData.Admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ItalianName { get; set; }
        public string GermanName { get; set; }
        public string FrenchName { get; set; }
        public string PolishName { get; set; }
        public string RussianName { get; set; }
        public string ArabicName { get; set; }
        public string Iso2 { get; set; }
        public string Iso3 { get; set; }
        public Nullable<int> CountryCode { get; set; }
    }
}
