//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicData.Admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaqLocalized
    {
        public int FaqId { get; set; }
        public int LanguageId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
    
        public virtual Faq Faq { get; set; }
        public virtual Language Language { get; set; }
    }
}
