//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicData.Admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeBanner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HomeBanner()
        {
            this.HomeBannerLocalizeds = new HashSet<HomeBannerLocalized>();
        }
    
        public int Id { get; set; }
        public string Photo { get; set; }
        public int DisplayOrder { get; set; }
        public bool Active { get; set; }
        public string VideoUrl { get; set; }
        public string Link { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeBannerLocalized> HomeBannerLocalizeds { get; set; }
    }
}
