//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicData.Admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Language()
        {
            this.AlbumLocalizeds = new HashSet<AlbumLocalized>();
            this.BannerLocalizeds = new HashSet<BannerLocalized>();
            this.CareerLocalizeds = new HashSet<CareerLocalized>();
            this.CityLocalizeds = new HashSet<CityLocalized>();
            this.FaqCategoryLocalizeds = new HashSet<FaqCategoryLocalized>();
            this.FaqLocalizeds = new HashSet<FaqLocalized>();
            this.HomeBannerLocalizeds = new HashSet<HomeBannerLocalized>();
            this.InfoPageCategoryLocalizeds = new HashSet<InfoPageCategoryLocalized>();
            this.InfoPageLocalizeds = new HashSet<InfoPageLocalized>();
            this.NewsLocalizeds = new HashSet<NewsLocalized>();
            this.MetaTagLocalizeds = new HashSet<MetaTagLocalized>();
        }
    
        public int Id { get; set; }
        public string LocalName { get; set; }
        public string CultureName { get; set; }
        public string FriendlyName { get; set; }
        public bool Active { get; set; }
        public int DisplayOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumLocalized> AlbumLocalizeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BannerLocalized> BannerLocalizeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareerLocalized> CareerLocalizeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CityLocalized> CityLocalizeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaqCategoryLocalized> FaqCategoryLocalizeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaqLocalized> FaqLocalizeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeBannerLocalized> HomeBannerLocalizeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoPageCategoryLocalized> InfoPageCategoryLocalizeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoPageLocalized> InfoPageLocalizeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsLocalized> NewsLocalizeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MetaTagLocalized> MetaTagLocalizeds { get; set; }
    }
}
