//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicData.Admin.Model
{
    using System;
    
    public enum SocialLinkTypes : int
    {
        Facebook = 1,
        LinkedIn = 2,
        GooglePlus = 3,
        Twitter = 4,
        YouTube = 5,
        Skype = 6
    }
}
