//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicData.Admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialLink
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Link { get; set; }
        public string CssClass { get; set; }
        public bool Active { get; set; }
    }
}
