//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicData.Admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int Id { get; set; }
        public int TestimonialSourceId { get; set; }
        public System.DateTime Date { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public int DisplayOrder { get; set; }
        public bool Active { get; set; }
    
        public virtual TestimonialSource TestimonialSource { get; set; }
    }
}
